CREATE TABLE `annual_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`year` int NOT NULL,
	`professional` text,
	`finance` text,
	`learning` text,
	`wellness` text,
	`relationships` text,
	`community` text,
	`creativity` text,
	`spirit` text,
	`basicNeeds` json,
	`nonNegotiables` json,
	`annualBudget` json,
	`knowledgeSkills` text,
	`passionsCallings` text,
	`naturalGifts` text,
	`problemsToSolve` text,
	`vennOverlap` text,
	`visionBoardContent` text,
	`missionStatement` text,
	`elevatorPitch` text,
	`contractName` text,
	`contractBe` text,
	`contractDo` text,
	`contractBecome` text,
	`contractGoals` json,
	`transformationTimeline` json,
	`notionDatabaseId` varchar(128),
	`notionToken` text,
	`googleCalendarId` varchar(256),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `annual_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `big_goals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`year` int NOT NULL,
	`position` int NOT NULL,
	`title` text,
	`description` text,
	`steps` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `big_goals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `content_calendar_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`weekNum` int NOT NULL,
	`entries` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `content_calendar_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `daily_entries` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`date` varchar(10) NOT NULL,
	`topPriorities` json,
	`timeSlots` json,
	`gratitude` json,
	`waterGlasses` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `daily_entries_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `monthly_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`year` int NOT NULL,
	`month` int NOT NULL,
	`themeWord` text,
	`wellnessHabit` text,
	`wellnessMinutes` int,
	`todos` text,
	`financialTargets` text,
	`shoppingList` text,
	`livingExpenses` text,
	`personalExpenses` text,
	`savings` text,
	`investment` text,
	`entertainment` text,
	`oneTimeExpenses` text,
	`businessCareerGoals` text,
	`wellnessGoals` text,
	`bookOfMonth` text,
	`birthdays` text,
	`actsOfKindness` text,
	`socialFollowers` json,
	`socialCampaigns` text,
	`socialCollaborations` text,
	`contentMapMonth` text,
	`contentMapPlatforms` json,
	`contentMapObjectives` json,
	`contentMapCampaigns` json,
	`contentMapPillars` json,
	`contentMapNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `monthly_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `weekly_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`year` int NOT NULL,
	`weekNumber` int NOT NULL,
	`weekStartDate` varchar(10) NOT NULL,
	`wordOfWeek` text,
	`affirmation` text,
	`bibleVerse` text,
	`bibleReference` text,
	`topBusinessGoals` text,
	`weekIntentions` text,
	`wellnessTasks` text,
	`moneyEarned` text,
	`moneySpent` text,
	`winsOfWeek` text,
	`notes` text,
	`socialPosts` json,
	`habitTracker` json,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `weekly_plans_id` PRIMARY KEY(`id`)
);
