import { useLocation } from "wouter";
import { ArrowLeft } from "lucide-react";

const EFFECTIVE_DATE = "June 30, 2026";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="mb-8">
      <h2 className="text-lg font-bold text-[#1a1a1a] mb-2">{title}</h2>
      <div className="text-[#5a4a3a] leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

function LegalShell({ title, children }: { title: string; children: React.ReactNode }) {
  const [, navigate] = useLocation();
  return (
    <div className="min-h-screen bg-[#faf8f5]">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <button
          onClick={() => navigate("/login")}
          className="flex items-center gap-2 text-sm text-[#8a7a6a] hover:text-[#1a1a1a] mb-8"
        >
          <ArrowLeft size={16} /> Back
        </button>
        <h1 className="text-3xl font-black text-[#1a1a1a] mb-1">{title}</h1>
        <p className="text-sm text-[#8a7a6a] mb-10">Effective {EFFECTIVE_DATE} · Be Do Become Wellness</p>
        {children}
      </div>
    </div>
  );
}

export function TermsPage() {
  return (
    <LegalShell title="Terms of Service">
      <Section title="1. Acceptance of Terms">
        By creating an account or using the BDB Digital Wellness Planner ("the App"), you agree to these
        Terms of Service. If you do not agree, do not use the App.
      </Section>
      <Section title="2. Eligibility">
        You must be at least 13 years old to create an account. By registering, you confirm that you meet
        this requirement and that the information you provide is accurate.
      </Section>
      <Section title="3. Your Account">
        You are responsible for safeguarding your password and for all activity under your account. Notify
        us immediately of any unauthorized use.
      </Section>
      <Section title="4. Acceptable Use">
        You agree not to misuse the App, including attempting to access another user's data, disrupting
        the service, or uploading unlawful, harassing, or harmful content in community features.
      </Section>
      <Section title="5. Zion AI">
        The App includes an AI assistant ("Zion") that provides planning suggestions, reminders, and
        reflections based on the information you provide. Zion's output is generated by a third-party
        large language model and is provided for informational and motivational purposes only — it is not
        professional, medical, financial, or legal advice.
      </Section>
      <Section title="6. Your Content">
        You retain ownership of the content you create in the App (goals, notes, journal entries, images).
        You grant us a limited license to store and process that content solely to provide the App's
        functionality, including generating your AI-powered summaries and reminders.
      </Section>
      <Section title="7. Termination">
        You may delete your account at any time from Settings, which permanently erases your data. We may
        suspend or terminate accounts that violate these Terms.
      </Section>
      <Section title="8. Disclaimer & Limitation of Liability">
        The App is provided "as is" without warranties of any kind. To the fullest extent permitted by
        law, Be Do Become Wellness is not liable for indirect, incidental, or consequential damages
        arising from your use of the App.
      </Section>
      <Section title="9. Changes to These Terms">
        We may update these Terms from time to time. Continued use of the App after changes take effect
        constitutes acceptance of the revised Terms.
      </Section>
      <Section title="10. Contact">
        Questions about these Terms can be sent to the contact address listed in the App's support
        section.
      </Section>
    </LegalShell>
  );
}

export function PrivacyPage() {
  return (
    <LegalShell title="Privacy Policy">
      <Section title="1. Information We Collect">
        Account information (name, email, date of birth, password — stored as a salted hash), planner
        content you create (goals, notes, journal entries, check-ins), and, if you connect them, data from
        third-party integrations you authorize (e.g. Google Calendar/Gmail, social media analytics).
      </Section>
      <Section title="2. How We Use Your Information">
        To provide and personalize the App, including Zion AI's planning suggestions and scheduled emails
        (morning briefings, weekly reviews, monthly reflections), to maintain account security (audit
        logs, login attempt monitoring), and to communicate service-related notices.
      </Section>
      <Section title="3. AI Processing">
        To generate Zion's responses, relevant planner content is sent to a third-party AI provider
        (Anthropic) for processing. This content is used to generate your response and is not used to
        train the provider's models under their API terms.
      </Section>
      <Section title="4. Data Sharing">
        We do not sell your personal information. We share data only with service providers who help us
        operate the App (hosting, email delivery, AI processing) under contractual confidentiality
        obligations, or when required by law.
      </Section>
      <Section title="5. Data Retention">
        We retain your data while your account is active. Accounts that are inactive for 2 years are
        automatically anonymized. You may request deletion or export of your data at any time from
        Settings.
      </Section>
      <Section title="6. Your Rights">
        You have the right to access, export, correct, and delete your personal data. Use the
        "Export My Data" and "Delete Account" options in Settings, or contact us directly.
      </Section>
      <Section title="7. Security">
        We use industry-standard safeguards including encrypted password storage, HTTPS transport,
        account lockout after repeated failed logins, and audit logging of security-relevant events.
      </Section>
      <Section title="8. Children's Privacy">
        The App is not directed to children under 13, and we do not knowingly collect personal information
        from anyone under 13.
      </Section>
      <Section title="9. Changes to This Policy">
        We may update this Privacy Policy periodically. Material changes will be communicated through the
        App.
      </Section>
      <Section title="10. Contact">
        Questions about this Privacy Policy can be sent to the contact address listed in the App's support
        section.
      </Section>
    </LegalShell>
  );
}
